-- Phase 9: fill missing public Bible book metadata for V1 book detail UI.
-- Conservative by design: only blank text fields and empty theme arrays are filled.

with source_metadata (id, short_description, overview, why_read, key_themes) as (
  values
    ('genesis', 'Origins, covenant, and the first promises of God.', 'Genesis begins the Bible story with creation, humanity, sin, and the family through whom God starts His covenant plan.', 'Read Genesis to understand the Bible''s foundations and the way God''s promises begin shaping everything that follows.', array['Beginnings', 'Covenant', 'Promise']),
    ('exodus', 'Deliverance, covenant, worship, and God''s presence.', 'Exodus tells how God rescues His people from slavery and teaches them to live as a people near His holy presence.', 'Read Exodus when you need to remember that God rescues, leads, and stays with His people.', array['Deliverance', 'Worship', 'Presence']),
    ('leviticus', 'Holiness, sacrifice, worship, and drawing near to God.', 'Leviticus shows how a holy God makes a way for His people to approach Him through worship, cleansing, and atonement.', 'Read Leviticus to better understand holiness, repentance, and the mercy behind God''s commands.', array['Holiness', 'Atonement', 'Worship']),
    ('numbers', 'A wilderness story of testing, mercy, and guidance.', 'Numbers follows God''s people through the wilderness with rebellion, correction, provision, and patient leadership from God.', 'Read Numbers for perspective on delay, discipline, and God''s faithfulness through hard seasons.', array['Wilderness', 'Trust', 'Guidance']),
    ('deuteronomy', 'A final call to remember, love, and obey God.', 'Deuteronomy gathers Moses'' final words and calls the people to covenant faithfulness shaped by remembered grace.', 'Read Deuteronomy when you need spiritual renewal and a steady reminder to love God wholeheartedly.', array['Remembering', 'Obedience', 'Covenant']),
    ('joshua', 'Courage, inheritance, and God''s kept promises.', 'Joshua tells how God brings His people into the promised land and gives them rest after long waiting.', 'Read Joshua for courage in new seasons and confidence that God keeps His word.', array['Courage', 'Inheritance', 'Faithfulness']),
    ('judges', 'Cycles of drift, rescue, and the need for a true king.', 'Judges shows a repeated pattern of compromise, oppression, rescue, and spiritual confusion among God''s people.', 'Read Judges to see the cost of drift and the deep need for faithful leadership and redemption.', array['Drift', 'Deliverance', 'Compromise']),
    ('ruth', 'A tender story of loyalty, grief, and redemption.', 'Ruth shows God''s quiet care through loss, kindness, faithfulness, and ordinary acts of covenant love.', 'Read Ruth for comfort in uncertain seasons and a reminder that God works through humble faithfulness.', array['Redemption', 'Loyalty', 'Provision']),
    ('1-samuel', 'Leadership, calling, waiting, and a heart for God.', '1 Samuel moves from Hannah and Samuel to Saul and David, exploring leadership and obedience before God.', 'Read 1 Samuel when you want wisdom for calling, waiting, and trusting God''s timing.', array['Leadership', 'Calling', 'Obedience']),
    ('2-samuel', 'David''s reign with promise, failure, and mercy.', '2 Samuel shows David''s kingdom in both strength and sorrow, holding together covenant promise and painful consequence.', 'Read 2 Samuel for an honest picture of leadership, repentance, and God''s covenant faithfulness.', array['Kingship', 'Repentance', 'Covenant']),
    ('1-kings', 'Wisdom, glory, division, and drifting hearts.', '1 Kings begins with Solomon and follows the fracture of the kingdom as hearts turn away from God.', 'Read 1 Kings to remember that outward success means little if the heart is not faithful.', array['Wisdom', 'Division', 'Faithfulness']),
    ('2-kings', 'Decline, warning, exile, and the cost of compromise.', '2 Kings follows Israel and Judah through rebellion, prophetic warning, and eventual exile.', 'Read 2 Kings for sober clarity about compromise and the seriousness of ignoring God''s voice.', array['Exile', 'Judgment', 'Prophets']),
    ('1-chronicles', 'A worship-shaped retelling centered on David.', '1 Chronicles revisits Israel''s story with attention to worship, identity, and David''s prepared heart.', 'Read 1 Chronicles to see how worship and spiritual heritage shape a people''s life with God.', array['Worship', 'David', 'Identity']),
    ('2-chronicles', 'Reform, prayer, worship, and returning to God.', '2 Chronicles follows Judah''s kings with a strong focus on the temple, prayer, and renewal.', 'Read 2 Chronicles for reminders that humble prayer and repentance still matter deeply.', array['Reform', 'Prayer', 'Renewal']),
    ('ezra', 'Restoration, scripture, worship, and rebuilding.', 'Ezra tells how God brings His people back from exile and rebuilds worship around His word.', 'Read Ezra when you need encouragement for rebuilding with spiritual renewal, not just outward progress.', array['Restoration', 'Scripture', 'Rebuilding']),
    ('nehemiah', 'Rebuilding with prayer, courage, and steady leadership.', 'Nehemiah follows the rebuilding of Jerusalem with prayerful leadership, opposition, and long-term reform.', 'Read Nehemiah for strength in responsible work, perseverance, and faithful rebuilding.', array['Leadership', 'Rebuilding', 'Perseverance']),
    ('esther', 'Courage and providence when God''s hand seems hidden.', 'Esther shows how deliverance can unfold through risk, timing, and quiet providence.', 'Read Esther to remember that God is still at work even when His presence feels hidden.', array['Providence', 'Courage', 'Deliverance']),
    ('job', 'Suffering, honesty, endurance, and God''s wisdom.', 'Job takes pain seriously and makes room for grief, questions, humility, and deeper trust in God.', 'Read Job when you need honest companionship in suffering without shallow answers.', array['Suffering', 'Endurance', 'Wisdom']),
    ('psalms', 'Songs, prayers, cries, and praise for the inner life.', 'Psalms gives language for worship, grief, trust, repentance, longing, and joy before God.', 'Read Psalms when you need help praying honestly and bringing your whole heart to God.', array['Prayer', 'Worship', 'Trust']),
    ('proverbs', 'Practical wisdom for choices, speech, work, and relationships.', 'Proverbs trains the heart in discernment, humility, diligence, and reverence for God.', 'Read Proverbs when you want grounded wisdom for everyday life and decision-making.', array['Wisdom', 'Discipline', 'Discernment']),
    ('ecclesiastes', 'A searching book about meaning, limits, and reverence.', 'Ecclesiastes looks honestly at work, pleasure, time, injustice, and the passing nature of life.', 'Read Ecclesiastes when you want a mature, honest look at what really lasts.', array['Meaning', 'Mortality', 'Reverence']),
    ('song-of-solomon', 'Poetry of love, delight, longing, and covenant affection.', 'Song of Solomon celebrates love with beauty, tenderness, longing, and commitment.', 'Read Song of Solomon to reflect on love as a gift and the beauty of faithful affection.', array['Love', 'Delight', 'Faithfulness']),
    ('isaiah', 'Holiness, judgment, comfort, and coming hope.', 'Isaiah moves from warning to comfort and keeps pointing toward redemption and the coming Servant-King.', 'Read Isaiah for a larger vision of God and a deeper hope in His saving work.', array['Holiness', 'Comfort', 'Hope']),
    ('jeremiah', 'Tears, warning, and hope in a new covenant.', 'Jeremiah speaks through collapse and stubbornness with sorrow, warning, and future covenant hope.', 'Read Jeremiah to stay tender before God in hard seasons and remember His mercy is not finished.', array['Repentance', 'Lament', 'Hope']),
    ('lamentations', 'Poetry of grief that still reaches for mercy.', 'Lamentations gives honest language for communal sorrow without letting go of hope in God''s compassion.', 'Read Lamentations when you need permission to grieve faithfully and wait for mercy.', array['Lament', 'Grief', 'Mercy']),
    ('ezekiel', 'Holiness, judgment, cleansing, and renewal.', 'Ezekiel confronts spiritual numbness and holds out hope for cleansing, restoration, and new life.', 'Read Ezekiel when you need awakening and hope that dry places can live again.', array['Holiness', 'Renewal', 'Restoration']),
    ('daniel', 'Faithfulness under pressure and hope in God''s kingdom.', 'Daniel combines exile stories and visions to show courageous loyalty to God under pressure.', 'Read Daniel for courage to stay faithful in a culture pulling in other directions.', array['Faithfulness', 'Courage', 'Kingdom']),
    ('hosea', 'Broken covenant, steadfast love, and pursuing mercy.', 'Hosea shows the depth of unfaithfulness and the persistence of God''s compassionate love.', 'Read Hosea to remember that God''s mercy continues to pursue wandering hearts.', array['Steadfast Love', 'Repentance', 'Mercy']),
    ('joel', 'A short call to repentance, prayer, and restored hope.', 'Joel moves from crisis to repentance and the promise of God''s Spirit and restoration.', 'Read Joel when you need a fresh call to prayer and hope that God can restore.', array['Repentance', 'Prayer', 'Restoration']),
    ('amos', 'Justice, righteousness, and true worship.', 'Amos confronts empty religion and reminds God''s people that worship and justice belong together.', 'Read Amos for a clear reminder that God cares about both devotion and integrity.', array['Justice', 'Righteousness', 'Integrity']),
    ('obadiah', 'A brief warning against pride and false security.', 'Obadiah speaks against pride, betrayal, and the illusion that injustice will go unseen.', 'Read Obadiah to remember that pride is fragile and God''s justice is sure.', array['Pride', 'Justice', 'Judgment']),
    ('jonah', 'Resistance, mercy, repentance, and compassion.', 'Jonah exposes the heart of a reluctant prophet and the surprising wideness of God''s mercy.', 'Read Jonah when you need to face resistance in your own heart and remember God''s compassion.', array['Mercy', 'Repentance', 'Obedience']),
    ('micah', 'Judgment, justice, humility, and promised hope.', 'Micah confronts corruption while calling God''s people back to humble and faithful living.', 'Read Micah for a strong call to justice, humility, and hope rooted in God.', array['Justice', 'Humility', 'Hope']),
    ('nahum', 'Judgment on cruelty and comfort for the oppressed.', 'Nahum announces the fall of violent power and reminds readers that God is not indifferent to evil.', 'Read Nahum when you need to remember that cruelty does not rule forever.', array['Justice', 'Comfort', 'Judgment']),
    ('habakkuk', 'Honest questions, waiting, and living by faith.', 'Habakkuk brings confusion to God and learns to stand in trust before circumstances improve.', 'Read Habakkuk when you need language for waiting and a steadier posture of faith.', array['Faith', 'Waiting', 'Trust']),
    ('zephaniah', 'Judgment that opens the way to refuge and renewal.', 'Zephaniah warns of judgment but also speaks of refuge, cleansing, and restored joy.', 'Read Zephaniah to hold together holy reverence and hopeful confidence in renewal.', array['Judgment', 'Refuge', 'Renewal']),
    ('haggai', 'A concise call to reordered priorities and renewed work.', 'Haggai challenges God''s people to stop neglecting what matters most and to begin again.', 'Read Haggai when you need to reset priorities and restart faithful work.', array['Priorities', 'Obedience', 'Courage']),
    ('zechariah', 'Visions, cleansing, return, and future hope.', 'Zechariah encourages a rebuilding people with vivid visions and promises of coming restoration.', 'Read Zechariah when unfinished work feels heavy and you need stronger hope.', array['Hope', 'Restoration', 'Cleansing']),
    ('malachi', 'A final call to wholehearted worship and faithfulness.', 'Malachi confronts spiritual weariness and calls God''s people back to sincere covenant life.', 'Read Malachi when devotion has grown dull and you need a loving wake-up call.', array['Faithfulness', 'Worship', 'Repentance']),
    ('matthew', 'Jesus as King, Teacher, and fulfillment of promise.', 'Matthew presents Jesus with rich teaching and strong links to the larger story of scripture.', 'Read Matthew when you want to follow Jesus more deliberately and see His kingdom clearly.', array['Kingdom', 'Discipleship', 'Fulfillment']),
    ('mark', 'A fast-moving gospel of action, authority, and discipleship.', 'Mark moves quickly through Jesus'' ministry and keeps the call to follow Him in clear view.', 'Read Mark for a direct, energetic portrait of Jesus and the cost of discipleship.', array['Authority', 'Discipleship', 'Action']),
    ('luke', 'A careful gospel of compassion, prayer, and good news.', 'Luke tells the story of Jesus with warmth, detail, mercy, and attention to the overlooked.', 'Read Luke when you want a fuller narrative of Jesus shaped by compassion and invitation.', array['Compassion', 'Prayer', 'Joy']),
    ('john', 'A warm, personal gospel centered on Jesus, belief, and eternal life.', 'John highlights who Jesus is through signs, conversations, and direct teaching. The tone is personal and reflective, making it especially approachable for steady daily reading.', 'John is strong for both new and returning readers because it keeps pointing back to the identity of Jesus and the invitation to believe and remain in Him.', array['Belief', 'Life in Christ', 'Love', 'Abiding']),
    ('acts', 'The early church, the Spirit''s power, and outward mission.', 'Acts follows the risen Jesus'' work through the Spirit as the gospel moves from Jerusalem outward.', 'Read Acts when you need courage, mission, and a larger vision of Spirit-led witness.', array['Holy Spirit', 'Mission', 'Witness']),
    ('romans', 'Grace, righteousness, the gospel, and transformed life.', 'Romans explains sin, justification, grace, and the shape of a life offered fully to God.', 'Read Romans when you want firmer confidence in the gospel and grace-filled obedience.', array['Grace', 'Righteousness', 'Transformation']),
    ('1-corinthians', 'A candid letter about church life, holiness, and love.', '1 Corinthians addresses division, worship, relationships, and resurrection hope in a messy church.', 'Read 1 Corinthians to see how the gospel speaks into real community struggles.', array['Holiness', 'Love', 'Resurrection']),
    ('2-corinthians', 'Weakness, comfort, integrity, and grace-filled ministry.', '2 Corinthians speaks openly about suffering, reconciliation, generosity, and strength in weakness.', 'Read 2 Corinthians when you need to see how grace meets pressure and weakness honestly.', array['Comfort', 'Integrity', 'Reconciliation']),
    ('galatians', 'Grace, freedom, and life led by the Spirit.', 'Galatians pushes back against every attempt to add human earning to the gospel.', 'Read Galatians when you need to come back to grace and live from freedom in Christ.', array['Grace', 'Freedom', 'Identity in Christ']),
    ('ephesians', 'Identity in Christ, unity, and spiritual strength.', 'Ephesians moves from the riches of salvation to the shape of a new life together in Christ.', 'Read Ephesians when you need to lift your eyes and remember who you are in Christ.', array['Identity in Christ', 'Unity', 'Grace']),
    ('philippians', 'A short letter full of joy, steadiness, humility, and Christ-centered focus.', 'Philippians combines affection, endurance, joy, humility, and practical encouragement. It is compact, readable, and deeply comforting.', 'Philippians works well for users who want encouragement, peace in difficulty, and a strong reminder to center life on Christ.', array['Joy', 'Peace', 'Humility', 'Steadfastness']),
    ('colossians', 'A compact letter lifting up the sufficiency of Christ.', 'Colossians calls the church back to the fullness of Christ when other voices compete for attention.', 'Read Colossians when you need to refocus on Christ and grow in steady maturity.', array['Supremacy of Christ', 'Fullness', 'Maturity']),
    ('1-thessalonians', 'Faithful endurance, holiness, and hopeful waiting.', '1 Thessalonians encourages a young church with tenderness, hope, and practical discipleship.', 'Read 1 Thessalonians when you need encouragement to remain hopeful and faithful.', array['Hope', 'Holiness', 'Endurance']),
    ('2-thessalonians', 'Clarity, steadiness, and disciplined hope.', '2 Thessalonians helps believers stay calm, sober, and faithful in the face of confusion or pressure.', 'Read 2 Thessalonians when fear or speculation is stealing steadiness from your faith.', array['Steadiness', 'Hope', 'Discernment']),
    ('1-timothy', 'Leadership, sound teaching, and godly character.', '1 Timothy gives practical guidance for prayer, teaching, leadership, and everyday godliness.', 'Read 1 Timothy for a clear picture of mature faith and trustworthy spiritual leadership.', array['Leadership', 'Godliness', 'Sound Teaching']),
    ('2-timothy', 'Endurance, courage, scripture, and faithful finishing.', '2 Timothy carries Paul''s final encouragements to remain courageous and loyal to the gospel.', 'Read 2 Timothy when you need strength to keep going without drifting.', array['Endurance', 'Courage', 'Scripture']),
    ('titus', 'Sound doctrine joined to visible good works.', 'Titus connects healthy teaching with practical godliness, leadership, and fruitful living.', 'Read Titus to remember that grace shapes both belief and daily behavior.', array['Grace', 'Good Works', 'Leadership']),
    ('philemon', 'A personal letter about reconciliation and gospel-shaped love.', 'Philemon shows the gospel working inside a strained relationship with dignity, mercy, and restored fellowship.', 'Read Philemon when you need to think about forgiveness, honor, and reconciliation in practice.', array['Reconciliation', 'Forgiveness', 'Love']),
    ('hebrews', 'Hold fast because Jesus is greater and fully sufficient.', 'Hebrews presents Jesus as the better priest, sacrifice, covenant, and lasting hope.', 'Read Hebrews when you feel tempted to drift and need a stronger vision of Christ.', array['Jesus is Better', 'Perseverance', 'Confidence']),
    ('james', 'Practical wisdom for speech, faith, and everyday obedience.', 'James presses faith into daily choices, words, suffering, prayer, and maturity.', 'Read James when you want grounded discipleship that shows up in ordinary life.', array['Wisdom', 'Obedience', 'Mature Faith']),
    ('1-peter', 'Holy hope for believers facing pressure and suffering.', '1 Peter encourages Christians to live with hope, humility, holiness, and endurance.', 'Read 1 Peter when faithfulness is costly and you need steadier hope.', array['Hope', 'Holiness', 'Suffering']),
    ('2-peter', 'Growth, discernment, and confidence in God''s promises.', '2 Peter urges believers to keep growing and to resist distortion and drift.', 'Read 2 Peter when you need discernment and renewed resolve to keep growing.', array['Discernment', 'Growth', 'Truth']),
    ('1-john', 'Assurance, truth, love, and walking in the light.', '1 John speaks warmly about assurance in Christ, obedience, love, and resistance to deception.', 'Read 1 John when you want steadier assurance and a clearer picture of real life with God.', array['Assurance', 'Love', 'Truth']),
    ('2-john', 'A short warning to hold truth and love together.', '2 John encourages believers to remain in Christ''s teaching without making peace with deception.', 'Read 2 John when you need to remember that real love stays rooted in truth.', array['Truth', 'Love', 'Faithfulness']),
    ('3-john', 'Encouragement about hospitality, truth, and leadership.', '3 John commends generous faithfulness and confronts proud, unhealthy leadership.', 'Read 3 John for a practical picture of encouragement, truth, and service-shaped influence.', array['Hospitality', 'Truth', 'Leadership']),
    ('jude', 'A brief call to contend for the faith with mercy.', 'Jude warns against destructive influence while urging believers to remain steadfast and prayerful.', 'Read Jude when you need alertness, mercy, and confidence that God keeps His people.', array['Discernment', 'Mercy', 'Perseverance']),
    ('revelation', 'Worship, endurance, judgment, and final hope in Christ.', 'Revelation strengthens the church with a larger vision of spiritual conflict, faithful witness, and final renewal.', 'Read Revelation when you need courage, worshipful perspective, and confidence in Christ''s final victory.', array['Hope', 'Endurance', 'Final Victory'])
),
target_rows as (
  select
    books.id,
    source.short_description,
    source.overview,
    source.why_read,
    source.key_themes
  from public.content_bible_books books
  join source_metadata source
    on source.id = books.id
  where btrim(books.short_description) = ''
     or btrim(books.overview) = ''
     or btrim(books.why_read) = ''
     or coalesce(array_length(books.key_themes, 1), 0) = 0
)
update public.content_bible_books as books
set
  short_description = case when btrim(books.short_description) = '' then target.short_description else books.short_description end,
  overview = case when btrim(books.overview) = '' then target.overview else books.overview end,
  why_read = case when btrim(books.why_read) = '' then target.why_read else books.why_read end,
  key_themes = case when coalesce(array_length(books.key_themes, 1), 0) = 0 then target.key_themes else books.key_themes end,
  updated_at = timezone('utc', now())
from target_rows as target
where books.id = target.id;

